services:
  balance-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:16.9-alpine3.22
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:8.0.2-alpine
    hostname: redis

  celery:
    build:
      context: .
    command: celery -A balance worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - balance-app

  celery-beat:
    build:
      context: .
    command: celery -A balance beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - balance-app