# Generated by Django 5.2.1 on 2025-05-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_type_transaction_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
